name: Build BoxedWine Web (WASM)

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build-boxedwine-web.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    container: emscripten/emsdk:latest  # official emscripten toolchain
    steps:
      - name: Checkout this repo (for artifacts)
        uses: actions/checkout@v4

      - name: Checkout BoxedWine source
        uses: actions/checkout@v4
        with:
          repository: danoon2/Boxedwine
          path: Boxedwine-src

      - name: Build BoxedWine web
        working-directory: Boxedwine-src/project/emscripten
        run: |
          chmod +x buildjs.sh || true
          ./buildjs.sh
          # Collect outputs (common names). Adjust paths if needed.
          mkdir -p /out
          # Find produced files
          find .. -maxdepth 3 -type f \( -name "boxedwine.js" -o -name "boxedwine.wasm" -o -name "boxedwine.data" \) -print -exec cp {} /out/ \;

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: boxedwine-web-runtime
          path: /out/*
          if-no-files-found: error
